Censio_CMS/Censio_CMS/Web_CMS/Controllers/GameChallengelevelController.cs
using Censio_CMS.Models;
using Censio_CMS.Web;
using Censio_CMS.Web.Filter;
using DataAccess.Data;
using Domain.Entities;
using Domain.Interfaces;
using m2ostnextservice.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace Censio_CMS.Controllers
{
    [SessionTimeout]
    public class GameChallengelevelController : Controller
    {
        int ID_ORGANIZATION = CommonFunctions.ID_ORGANIZATION;
        private readonly db_censio_betaContext DbContext;
        AESAlgorithm ency = new AESAlgorithm();
        private readonly IUnitOfWork _unitOfWork;
        string hrefURL = Startup.GethrefURL();
        private readonly IWebHostEnvironment webHostEnvironment;
        public GameChallengelevelController(IUnitOfWork unitOfWork, db_censio_betaContext context, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            DbContext = context;
            webHostEnvironment = hostEnvironment;
        }

        public ActionResult Index()
        {
            var model = (from T in this.DbContext.TblGameChallengelevel
                         join S in this.DbContext.TblGame on T.IdGame equals S.IdGame
                       
                         where T.IdOrganization == ID_ORGANIZATION 
                         select new
                         {

                             S.GameName,
                             T.IdLevel,
                             T.IdGame,
                             T.ChallengeName,
                             T.ChallengeSmallImgUrl,
                             T.IdOrganization,
                             T.ChallengeBigImgUrl,
                             T.IsActive,
                             T.UpdatedDateTime,
                             T.BigImgText,
                             T.ChallengeIntroMessage,
                             T.BottomCompleteMessage,
                             T.BottomFailMessage,
                             T.ChallengePieceMapImgUrl,
                             T.ChallengePieceMapMsg,
                             T.AgainPlayCoins,
                             T.AttemptsAllowed,
                             T.AttemptTimer,
                             T.ThirdGameScore,
                             T.SpecialPoint,
                             T.NotBackingOutMsg,
                             T.SuperpowerCoinGame3,
                         }).Select(X => new GameChallengelevelModel
                         {
                             IdLevel = X.IdLevel,
                             IdGame = X.IdGame,
                             GameName = X.GameName,
                             ChallengeName = X.ChallengeName,
                             ChallengeSmallImgUrl = X.ChallengeSmallImgUrl,
                             IdOrganization = X.IdOrganization,
                             ChallengeBigImgUrl = X.ChallengeBigImgUrl,
                             IsActive = X.IsActive,
                             UpdatedDateTime = X.UpdatedDateTime,
                             BigImgText = X.BigImgText,
                             ChallengeIntroMessage = X.ChallengeIntroMessage,
                             BottomCompleteMessage = X.BottomCompleteMessage,
                             BottomFailMessage = X.BottomFailMessage,
                             ChallengePieceMapImgUrl = X.ChallengePieceMapImgUrl,
                             ChallengePieceMapMsg = X.ChallengePieceMapMsg,
                             AgainPlayCoins = X.AgainPlayCoins,
                             AttemptTimer = X.AttemptTimer,
                             ThirdGameScore = X.ThirdGameScore,
                             SpecialPoint = X.SpecialPoint,
                             NotBackingOutMsg = X.NotBackingOutMsg,
                             SuperpowerCoinGame3 = X.SuperpowerCoinGame3,
                             AttemptsAllowed = X.AttemptsAllowed,
                         }).ToList();

            ViewBag.PageName = "Game Challengelevel List";


            return View(model);

        }


        public ActionResult Edit(int? id)
        {
            GameChallengelevelModel model = new GameChallengelevelModel();

            TblGameChallengelevel tblData = new TblGameChallengelevel();

            tblData = this.DbContext.TblGameChallengelevel.Find(id);

            if (model == null)
            {
                return HttpNotFound();
            }
            else
            {
                model.IdLevel = tblData.IdLevel;
                model.ChallengeName = tblData.ChallengeName;
                model.IdGame = tblData.IdGame;
                model.ChallengeSmallImgUrl = tblData.ChallengeSmallImgUrl;
                model.ChallengeBigImgUrl = tblData.ChallengeBigImgUrl;
                model.BigImgText = tblData.BigImgText;
                model.ChallengeIntroMessage = tblData.ChallengeIntroMessage;
                model.BottomCompleteMessage = tblData.BottomCompleteMessage;
                model.BottomFailMessage = tblData.BottomFailMessage;
                model.ChallengePieceMapImgUrl = tblData.ChallengePieceMapImgUrl;
                model.ChallengePieceMapMsg = tblData.ChallengePieceMapMsg;
                model.AgainPlayCoins = tblData.AgainPlayCoins;
                model.AttemptsAllowed = tblData.AttemptsAllowed;
                model.AttemptTimer = tblData.AttemptTimer;
                model.IdOrganization = tblData.IdOrganization;
                model.IsActive = tblData.IsActive;
                model.UpdatedDateTime = tblData.UpdatedDateTime;
                model.ThirdGameScore = tblData.ThirdGameScore;
                model.SpecialPoint = tblData.SpecialPoint;
                model.NotBackingOutMsg = tblData.NotBackingOutMsg;
                model.SuperpowerCoinGame3 = tblData.SuperpowerCoinGame3;
            }

            ViewBag.modelTitle = "Edit";
            model.GameNameList = DbContext.TblGameMaster.ToList().Select(X => new SelectListItem
            {
                Text = X.GameName,
                Value = X.IdGame.ToString()
            });

            return View("Create", model);

        }

        private ActionResult HttpNotFound()
        {
            throw new NotImplementedException();
        }

        public ActionResult Create()
        {
            GameChallengelevelModel model = new GameChallengelevelModel();

            model.GameNameList = DbContext.TblGameMaster.ToList().Select(X => new SelectListItem
            {
                Text = X.GameName,
                Value = X.IdGame.ToString()
            });
            ViewBag.modelTitle = "Add";
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> AddEditAsync(TblGameChallengelevel model)
        {
            model.IdOrganization = (int)ID_ORGANIZATION;
            model.UpdatedDateTime = DateTime.UtcNow;
            model.IdCmsUser = HttpContext.Session.GetInt32("userid");
            try
            {


                var files = HttpContext.Request.Form.Files;
                if (model.IdLevel != 0)
                {
                    TblGameChallengelevel objData = (from c in this.DbContext.TblGameChallengelevel
                                                     where c.IdLevel == model.IdLevel
                                                        select c).FirstOrDefault();
                    if (objData != null)
                    {
                        for (int i = 0; i < files.Count; ++i)
                        {
                            if (files[i].Name == "ChallengeSmallImgUrlfile")
                            {
                                var file = files[i];
                                var allowedExtensions = new[] { ".Jpg", ".png", ".jpg", "jpeg", ".svg"};
                                var uploads = Path.Combine(webHostEnvironment.WebRootPath, "UploadeImage/GameChallengelevel/ChallengeSmallImgUrl");
                                if (files[i].Length > 0)
                                {
                                    var ext = Path.GetExtension(files[i].FileName);
                                    if (allowedExtensions.Contains(ext))
                                    {
                                        var fileName = model.IdOrganization + "_" + Path.GetFileName(files[i].FileName);
                                        HttpContext.Session.SetString("BuildingImgFileName", fileName);

                                        using (var fileStream = new FileStream(Path.Combine(uploads, fileName), FileMode.Create))
                                        {
                                            await file.CopyToAsync(fileStream);
                                            model.ChallengeSmallImgUrl = "UploadeImage/GameChallengelevel/ChallengeSmallImgUrl/"+fileName;
                                        }
                                    }
                                    else
                                    {
                                        return Json(new { Message = "Sorry!! Uploade only .Jpg, .png, jpeg, .svg", data = 3 });
                                    }

                                }
                              
                            }
                            if (files[i].Name == "ChallengeBigImgUrlfile")
                            {
                                var file = files[i];
                                var allowedExtensions = new[] { ".Jpg", ".png", ".jpg", "jpeg", ".svg"};
                                var uploads = Path.Combine(webHostEnvironment.WebRootPath, "UploadeImage/GameChallengelevel/ChallengeBigImgUrl");
                                if (files[i].Length > 0)
                                {

Censio_CMS/Censio_CMS/Web_CMS/Views/GameChallengelevel/Create.cshtml
@model Censio_CMS.Models.GameChallengelevelModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block full">
    <div class="block-title">
        <button type="button" onclick="location.href='@Url.Action("Index", "GameChallengelevel")'" class="btn btn-primary" style="float: right; margin: 0; margin-right: 10px; margin-top: 9px; padding: 1px 13px;" data-dismiss="modal" aria-hidden="true">Back</button>
        <h2><strong>@ViewBag.modelTitle Game Challengelevel</strong> </h2>
    </div>
    <div class="table-responsive">

        <form id="form" class="push">

            <div class="modal-body">
                <div id="myAlert">
                </div>
                <div class="loader "> <img src="~/img/Loader.gif" style="height:50px;width:50px" /></div>
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">

                        <div class="form-group">
                            <label for="Industry_Name">Game Name</label>
                            @Html.TextBoxFor(m => m.IdLevel, new { @id = "IdLevel", @style = "display: none;" })
                            @Html.DropDownListFor(m => m.IdGame, new SelectList(Model.GameNameList, "Value", "Text"), "", new { @id = "IdGame", @class = "form-control", @onchange = "Gamechange();" })

                        </div>

                        <div class="form-group">
                            <label for="password">ChallengeName</label>
                            @Html.TextBoxFor(m => m.ChallengeName, new { @id = "ChallengeName", @class = "form-control" })

                        </div>

                        <div class="form-group">
                            <div class="col-sm-6">
                                <label for="checkout-payment-name">ChallengeSmallImgUrl</label>
                                @Html.TextBoxFor(m => m.ChallengeSmallImgUrl, new { @id = "ChallengeSmallImgUrl", @style = "display: none;" })
                                <input type="file" title="Upload File" class="form-control" id="ChallengeSmallImgUrlfile" name="file" onchange="ChallengeSmallImgUrlshow(this)" />
                            </div>

                            <div class="col-sm-6">
                                <img id="ChallengeSmallImgUrl_img" style="height:100px;width:100px;" class="form-control" Style="border:solid" />
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-6">
                                <label for="checkout-payment-name">ChallengeBigImgUrl</label>
                                @Html.TextBoxFor(m => m.ChallengeBigImgUrl, new { @id = "ChallengeBigImgUrl", @style = "display: none;" })
                                <input type="file" title="Upload File" class="form-control" id="ChallengeBigImgUrlfile" name="file" onchange="ChallengeBigImgUrlshow(this)" />
                            </div>

                            <div class="col-sm-6">
                                <img id="ChallengeBigImgUrl_img" style="height:100px;width:100px;" class="form-control" Style="border:solid" />
                            </div>
                        </div>


                        <div class="form-group">
                            <label for="password">BigImgText</label>
                            @Html.TextAreaFor(m => m.BigImgText, new { @id = "BigImgText", @class = "form-control" })

                        </div>

                        <div class="form-group">
                            <label for="password">ChallengeIntroMessage</label>
                            @Html.TextAreaFor(m => m.ChallengeIntroMessage, new { @id = "ChallengeIntroMessage", @class = "form-control" })

                        </div>

                        <div class="form-group">
                            <label for="password">BottomCompleteMessage</label>
                            @Html.TextAreaFor(m => m.BottomCompleteMessage, new { @id = "BottomCompleteMessage", @class = "form-control" })

                        </div>

                        <div class="form-group">
                            <label for="password">BottomFailMessage</label>
                            @Html.TextAreaFor(m => m.BottomFailMessage, new { @id = "BottomFailMessage", @class = "form-control" })

                        </div>


                        <div class="form-group">
                            <div class="col-sm-6">
                                <label for="checkout-payment-name">ChallengePieceMapImgUrl</label>
                                @Html.TextBoxFor(m => m.ChallengePieceMapImgUrl, new { @id = "ChallengePieceMapImgUrl", @style = "display: none;" })
                                <input type="file" title="Upload File" class="form-control" id="ChallengePieceMapImgUrlfile" name="file" onchange="ChallengePieceMapImgUrlshow(this)" />
                            </div>

                            <div class="col-sm-6">
                                <img id="ChallengePieceMapImgUrl_img" style="height:100px;width:100px;" class="form-control" Style="border:solid" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password">ChallengePieceMapMsg</label>
                            @Html.TextAreaFor(m => m.ChallengePieceMapMsg, new { @id = "ChallengePieceMapMsg", @class = "form-control" })

                        </div>
                        <div class="form-group">
                            <label for="password">NotBackingOutMsg</label>
                            @Html.TextAreaFor(m => m.NotBackingOutMsg, new { @id = "NotBackingOutMsg", @class = "form-control" })

                        </div>
                        <div class="form-group">
                            <label for="password">AgainPlayCoins</label>
                            @Html.TextBoxFor(m => m.AgainPlayCoins, new { @id = "AgainPlayCoins", @class = "form-control" })

                        </div>

                        <div class="form-group">
                            <label for="password">AttemptsAllowed</label>
                            @Html.TextBoxFor(m => m.AttemptsAllowed, new { @id = "AttemptsAllowed", @class = "form-control" })

                        </div>


                        <div class="form-group">
                            <label for="password">AttemptTimer</label>
                            @Html.TextBoxFor(m => m.AttemptTimer, new { @id = "AttemptTimer", @class = "form-control" })

                        </div>

                        <div style='display:none;' id='Game3'>

                            <div class="form-group">
                                <label for="password">Third GameScore</label>
                                @Html.TextBoxFor(m => m.ThirdGameScore, new { @id = "ThirdGameScore", @class = "form-control" })

                            </div>

                            <div class="form-group">
                                <label for="password">Special Point</label>
                                @Html.TextBoxFor(m => m.SpecialPoint, new { @id = "SpecialPoint", @class = "form-control" })

                            </div>

                            <div class="form-group">
                                <label for="password">SuperpowerCoin Game3</label>
                                @Html.TextBoxFor(m => m.SuperpowerCoinGame3, new { @id = "SuperpowerCoinGame3", @class = "form-control" })

                            </div>
                        </div>
                        <div class="form-group">
                            <label for="checkout-payment-name">Status</label>
                            @Html.DropDownListFor(m => m.IsActive, new List<SelectListItem>
                                   {
                                   new SelectListItem{ Text="Active", Value = "A" },
                                   new SelectListItem{ Text="Deactive", Value = "D" }}, new { @class = "form-control", @style = "width:100%;", @id = "IsActive" })
                        </div>

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="btn" class="btn btn-effect-ripple btn-sm btn-success">Save</button>
                <button type="button" onclick="Close();" class="btn btn-effect-ripple btn-sm btn-danger">Cancel</button>
            </div>
        </form>
    </div>
</div>
<script src="~/js/Jquery3.5.1.js"></script>

<script>
    $(document).ready(function () {
        if ($("#ChallengeSmallImgUrl").val() != "") {
            $('#ChallengeSmallImgUrl_img').attr('src', $("#ChallengeSmallImgUrl").val());
        }
        if ($("#ChallengeBigImgUrl").val() != "") {
            $('#ChallengeBigImgUrl_img').attr('src', $("#ChallengeBigImgUrl").val());
        }
        if ($("#ChallengePieceMapImgUrl").val() != "") {
            $('#ChallengePieceMapImgUrl_img').attr('src', $("#ChallengePieceMapImgUrl").val());
        }

        $('#btn').on('click', function () {
            debugger;
            var valid = $("#form").valid();
            if (valid == true) {
                AddEdit();
            }
        });

        $("#Acclimateform").validate({
            //rules: {


            //    Url: "required",
            //    IsActive: "required",

            //},
            //messages: {


            //    Url: "Please Uploade Image ",
            //    IsActive: "Please Select a Status",
            //}
        })
    });



</script>
<style type="text/css">
    .loader {
        display: none;
        position: absolute;
        top: 75%;
        left: 50%;
        margin: -75px 0px 0px -50px;
    }
</style>
<script src="~/AppJavascript/GameChallengelevel.js"></script>

Censio_CMS/Censio_CMS/Web_CMS/Views/GameChallengelevel/Index.cshtml
@{ var hrefURL = Censio_CMS.Startup.GethrefURL();}
@model IEnumerable<Censio_CMS.Models.GameChallengelevelModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block full">
    <div class="block-title">
        <h2><strong> @ViewBag.PageName</strong> </h2>
    </div>
    <div class="table-responsive">

        <button type="button" onclick="location.href='@Url.Action("Create", "GameChallengelevel")'" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i>Add</button>
        <table id="GameChallengelevel" class="table table-vcenter table-condensed table-bordered">
            <thead>
                <tr>
                    <th class="text-center">Id</th>
                    <th class="text-center">GameName</th>
                    <th class="text-center">ChallengeName</th>
                    <th class="text-center">ChallengeSmallImgUrl</th>
                    <th class="text-center">ChallengeBigImgUrl</th>
                    <th class="text-center">BigImgText</th>
                    <th class="text-center">ChallengeIntroMessage</th>
                    <th class="text-center">BottomCompleteMessage</th>
                    <th class="text-center">BottomFailMessage</th>
                    <th class="text-center">ChallengePieceMapImgUrl</th>
                    <th class="text-center">ChallengePieceMapMsg</th>
                    <th class="text-center">NotBackingOutMsg</th>
                    <th class="text-center">AgainPlayCoins</th>
                    <th class="text-center">AttemptsAllowed</th>
                    <th class="text-center">AttemptTimer</th>
                    <th class="text-center">Third GameScore</th>
                    <th class="text-center">Special Point</th>
                    <th class="text-center">SuperpowerCoin Game3</th>

                    <th class="text-center">Status</th>
                    <th class="text-center">Date and Time</th>
                    <th class="text-center">Actions</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.IdLevel)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.GameName)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.ChallengeName)</td>
                    <td class="text-center"><img src="@(hrefURL  + item.ChallengeSmallImgUrl)" alt=" " height=100 width=100 /></td>
                    <td class="text-center"><img src="@(hrefURL + item.ChallengeBigImgUrl)" alt=" " height=100 width=100 /></td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.BigImgText)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.ChallengeIntroMessage)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.BottomCompleteMessage)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.BottomFailMessage)</td>
                    <td class="text-center"><img src="@(hrefURL + item.ChallengePieceMapImgUrl)" alt=" " height=100 width=100 /></td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.ChallengePieceMapMsg)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.NotBackingOutMsg)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.AgainPlayCoins)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.AttemptsAllowed)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.AttemptTimer)</td>


                    <td class="text-center">@Html.DisplayFor(modelItem => item.ThirdGameScore)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.SpecialPoint)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.SuperpowerCoinGame3)</td>
                    @if (item.IsActive == "A")
                    {
                        <td class="text-center">Active</td>
                    }
                    else
                    {
                        <td class="text-center"> DeActive</td>
                    }

                    <td class="text-center">@Html.DisplayFor(modelItem => item.UpdatedDateTime)</td>
                    <td class="text-center">
                        <div class="btn-group">
                            @Html.ActionLink("Edit", "Edit", new { id = item.IdLevel }, new { @title = "Edit", @class = "glyphicon glyphicon-pencil" })
                            @*<a href="javascript:void(0)" onclick="GetAddEdit(@item.Id_Industry);" data-toggle="tooltip" title="Edit" class="btn btn-effect-ripple btn-xs btn-success"><i class="material-icons">create</i></a>*@

                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<style type="text/css">

    .truncate {
        max-width: 200px;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }
</style>


<script src="~/AppJavascript/GameChallengelevel.js"></script>