Censio_CMS/Censio_CMS/Web_CMS/Controllers/Game5AttemptdataController.cs
using Censio_CMS.Models;
using Censio_CMS.Web;
using Censio_CMS.Web.Filter;
using DataAccess.Data;
using Domain.Entities;
using Domain.Interfaces;
using m2ostnextservice.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Censio_CMS.Controllers
{
    [SessionTimeout]
    public class Game5AttemptdataController : Controller
    {
        int ID_ORGANIZATION = CommonFunctions.ID_ORGANIZATION;
        private readonly db_censio_betaContext DbContext;
        AESAlgorithm ency = new AESAlgorithm();
        private readonly IUnitOfWork _unitOfWork;
        string hrefURL = Startup.GethrefURL();
        private readonly IWebHostEnvironment webHostEnvironment;
        public Game5AttemptdataController(IUnitOfWork unitOfWork, db_censio_betaContext context, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            DbContext = context;
            webHostEnvironment = hostEnvironment;
        }

        public ActionResult Index()
        {
            var model = (from T in this.DbContext.TblGameAttemptdata
                         join S in this.DbContext.TblGameChallengelevel on T.IdLevel equals S.IdLevel
                         join U in this.DbContext.TblGame on T.IdGame equals U.IdGame
                        
                         where T.IdOrganization == ID_ORGANIZATION && T.IdGame==5
                         select new
                         {
                          
                             U.GameName,
                             S.ChallengeName,
                             T.IdAttempt,
                             T.IdLevel,
                             T.AttemptNo,
                             T.IdGame,
                             T.GoldCoins,
                             T.IdBehavior,
                             T.BehaviorScore,
                             T.TimeInSecond,
                             T.ChallengeCompletedTime1,
                             T.RewardCoinsTime1,
                             T.ChallengeCompletedTime2,
                             T.RewardCoinsTime2,
                             T.FailAttemptMessage,
                             T.SuccessAttemptMessage,
                             T.IdOrganization,
                             T.IsActive,
                             T.UpdatedDateTime,
                             T.Game5Behaviors,
                         }).Select(X => new GameAttemptdataModel
                         {
                            
                             GameName = X.GameName,
                             ChallengeName = X.ChallengeName,
                             IdAttempt = X.IdAttempt,
                             IdLevel = X.IdLevel,
                             AttemptNo = X.AttemptNo,
                             IdGame = X.IdGame,
                             GoldCoins = X.GoldCoins,
                             IdBehavior = X.IdBehavior,
                             BehaviorScore = X.BehaviorScore,
                             TimeInSecond = X.TimeInSecond,
                             ChallengeCompletedTime1 = X.ChallengeCompletedTime1,
                             RewardCoinsTime1 = X.RewardCoinsTime1,
                             ChallengeCompletedTime2 = X.ChallengeCompletedTime2,
                             RewardCoinsTime2 = X.RewardCoinsTime2,
                             FailAttemptMessage = X.FailAttemptMessage,
                             SuccessAttemptMessage = X.SuccessAttemptMessage,
                             IdOrganization = X.IdOrganization,
                             IsActive = X.IsActive,
                             UpdatedDateTime = X.UpdatedDateTime,
                             Game5Behaviors = X.Game5Behaviors,
                         }).ToList();

            ViewBag.PageName = "Game5 Attemptdata List";


            return View(model);

        }


        public ActionResult Edit(int? id)
        {
            GameAttemptdataModel model = new GameAttemptdataModel();

            TblGameAttemptdata tblData = new TblGameAttemptdata();

            tblData = this.DbContext.TblGameAttemptdata.Find(id);

            if (model == null)
            {
                return HttpNotFound();
            }
            else
            {
                model.IdAttempt = tblData.IdAttempt;
                model.IdLevel = tblData.IdLevel;
                model.AttemptNo = tblData.AttemptNo;
                model.IdGame = tblData.IdGame;
                model.GoldCoins = tblData.GoldCoins;
                model.BehaviorScore = tblData.BehaviorScore;
                model.TimeInSecond = tblData.TimeInSecond;
                model.ChallengeCompletedTime1 = tblData.ChallengeCompletedTime1;
                model.RewardCoinsTime1 = tblData.RewardCoinsTime1;
                model.ChallengeCompletedTime2 = tblData.ChallengeCompletedTime2;
                model.RewardCoinsTime2 = tblData.RewardCoinsTime2;
                model.FailAttemptMessage = tblData.FailAttemptMessage;
                model.SuccessAttemptMessage = tblData.SuccessAttemptMessage;
                model.IdOrganization = tblData.IdOrganization;
                model.IsActive = tblData.IsActive;
                model.UpdatedDateTime = tblData.UpdatedDateTime;
                model.Game5Behaviors = tblData.Game5Behaviors;
            }

            ViewBag.Game5Behaviors = model.Game5Behaviors;

            TempData["Behaviors"] = new SelectList(DbContext.TblBehaviorElement.Where(x => x.Status == "A").ToList(), "IdBehavior", "BehaviorElement");
            ViewBag.modelTitle = "Edit"; ViewBag.gameid = model.IdGame;
            

            model.GameList = DbContext.TblGameMaster.Where(x=>x.IdGame==5).ToList().Select(X => new SelectListItem
            {
                Text = X.GameName,
                Value = X.IdGame.ToString()
            });

            model.ChallengeNameList = DbContext.TblGameChallengelevel.ToList().Where(x => x.IdOrganization == ID_ORGANIZATION && x.IsActive == "A").Select(X => new SelectListItem
            {
                Text = X.ChallengeName,
                Value = X.IdLevel.ToString()
            });
            return View("Create", model);

        }

        private ActionResult HttpNotFound()
        {
            throw new NotImplementedException();
        }

        public ActionResult Create()
        {
            GameAttemptdataModel model = new GameAttemptdataModel();
            TempData["Behaviors"] = new SelectList(DbContext.TblBehaviorElement.Where(x => x.Status == "A").ToList(), "IdBehavior", "BehaviorElement");
          

            model.GameList = DbContext.TblGameMaster.Where(x => x.IdGame == 5).ToList().Select(X => new SelectListItem
            {
                Text = X.GameName,
                Value = X.IdGame.ToString()
            });

            model.ChallengeNameList = DbContext.TblGameChallengelevel.ToList().Where(x => x.IdOrganization == ID_ORGANIZATION && x.IsActive == "A").Select(X => new SelectListItem
            {
                Text = X.ChallengeName,
                Value = X.IdLevel.ToString()
            });
            ViewBag.modelTitle = "Add";
            return View(model);
        }

        public ActionResult FillChallenge(int idGame)
        {
            var Challenges = this.DbContext.TblGameChallengelevel.Where(c => c.IdGame == idGame).ToList();
            return Json(Challenges);
        }


        [HttpPost]
        public ActionResult AddEdit(TblGameAttemptdata model)
        {

            try
            {

                model.IdOrganization = (int)ID_ORGANIZATION;
                model.UpdatedDateTime = DateTime.UtcNow;
                model.IdCmsUser = HttpContext.Session.GetInt32("userid");



                if (model.IdAttempt != 0)
                {
                    _unitOfWork.GameAttemptdata.Update(model);
                    _unitOfWork.Complete();
                    return Json(new { Message = "Successfully Updated", data = 1 });
                }
                else
                {
                    _unitOfWork.GameAttemptdata.Add(model);
                    _unitOfWork.Complete();
                    return Json(new { Message = "Successfully Added", data = 2 });
                }

            }
            catch (Exception ex)
            {

                return Json(new { Message = "error", data = 3 });
            }

        }
    }
}

Censio_CMS/Censio_CMS/Web_CMS/Views/Game5Attemptdata/Create.cshtml
@model Censio_CMS.Models.GameAttemptdataModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block full">
    <div class="block-title">
        <button type="button" onclick="location.href='@Url.Action("Index", "Game5Attemptdata")'" class="btn btn-primary" style="float: right; margin: 0; margin-right: 10px; margin-top: 9px; padding: 1px 13px;" data-dismiss="modal" aria-hidden="true">Back</button>
        <h2><strong>@ViewBag.modelTitle Game5 Attemptdata</strong> </h2>
    </div>
    <div class="table-responsive">

        <form id="form" class="push">

            <div class="modal-body">
                <div id="myAlert">
                </div>
                <div class="loader "> <img src="~/img/Loader.gif" style="height:50px;width:50px" /></div>
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">
                        <div class="form-group">
                            <label for="Industry_Name">Game Name</label>
                            @Html.TextBoxFor(m => m.IdAttempt, new { @id = "IdAttempt", @style = "display: none;" })
                            @Html.DropDownListFor(m => m.IdGame, new SelectList(Model.GameList, "Value", "Text"), "", new { @id = "IdGame", @class = "form-control", @onchange = "FillChallenge()" })

                        </div>
                        @if (@ViewBag.modelTitle == "Edit")
                        {
                            <div class="form-group">
                                <label for="Industry_Name">Challenge Name</label>

                                @Html.DropDownListFor(m => m.IdLevel, new SelectList(Model.ChallengeNameList, "Value", "Text"), "", new { @id = "IdLevel", @class = "form-control" })

                            </div>
                        }
                        else
                        {
                            <div class="form-group">
                                <label for="checkout-payment-name">Challenge Name</label>
                                @Html.DropDownListFor(m => m.IdLevel, new SelectList(Enumerable.Empty<SelectListItem>(), "IdLevel", "ChallengeName"), "", new { @id = "IdLevel", @class = "form-control" })

                            </div>
                        }

                       
                    <div class="form-group">
                        <label for="Industry_Name">Game5 Behavior Element</label>
                        @Html.DropDownList("idbehavior", (IEnumerable<SelectListItem>)TempData["Behaviors"], new { multiple = "multiple", style = "max-height:100px;width:500px;" })
                        <input type="hidden" id="hidSelectedOptions" value="@ViewBag.Game5Behaviors" />
                    </div>


                        <div class="form-group">
                            <label for="password">AttemptNo</label>
                            @Html.TextBoxFor(m => m.AttemptNo, new { @id = "AttemptNo", @class = "form-control" })

                        </div>
                        <div class="form-group">
                            <label for="password">GoldCoins</label>
                            @Html.TextBoxFor(m => m.GoldCoins, new { @id = "GoldCoins", @class = "form-control" })

                        </div>

                        <div class="form-group">
                            <label for="password">BehaviorScore</label>
                            @Html.TextBoxFor(m => m.BehaviorScore, new { @id = "BehaviorScore", @class = "form-control" })

                        </div>


                        <div class="form-group">
                            <label for="password">TimeInSecond</label>
                            @Html.TextBoxFor(m => m.TimeInSecond, new { @id = "TimeInSecond", @class = "form-control" })

                        </div>


                        @*<div class="form-group">
                            <label for="password">ChallengeCompletedTime1</label>
                            @Html.TextBoxFor(m => m.ChallengeCompletedTime1, new { @id = "ChallengeCompletedTime1", @class = "form-control" })

                        </div>

                        <div class="form-group">
                            <label for="password">RewardCoinsTime1</label>
                            @Html.TextBoxFor(m => m.RewardCoinsTime1, new { @id = "RewardCoinsTime1", @class = "form-control" })

                        </div>

                        <div class="form-group">
                            <label for="password">ChallengeCompletedTime2</label>
                            @Html.TextBoxFor(m => m.ChallengeCompletedTime2, new { @id = "ChallengeCompletedTime2", @class = "form-control" })

                        </div>

                        <div class="form-group">
                            <label for="password">RewardCoinsTime2</label>
                            @Html.TextBoxFor(m => m.RewardCoinsTime2, new { @id = "RewardCoinsTime2", @class = "form-control" })

                        </div>

                        <div class="form-group">
                            <label for="password">FailAttemptMessage</label>
                            @Html.TextAreaFor(m => m.FailAttemptMessage, new { @id = "FailAttemptMessage", @class = "form-control" })

                        </div>




                        <div class="form-group">
                            <label for="password">SuccessAttemptMessage</label>
                            @Html.TextAreaFor(m => m.SuccessAttemptMessage, new { @id = "SuccessAttemptMessage", @class = "form-control" })

                        </div>*@


                        <div class="form-group">
                            <label for="checkout-payment-name">Status</label>
                            @Html.DropDownListFor(m => m.IsActive, new List<SelectListItem>
                                   {
                                   new SelectListItem{ Text="Active", Value = "A" },
                                   new SelectListItem{ Text="Deactive", Value = "D" }}, new { @class = "form-control", @style = "width:100%;", @id = "IsActive" })
                        </div>

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="btn" class="btn btn-effect-ripple btn-sm btn-success">Save</button>
                <button type="button" onclick="Close();" class="btn btn-effect-ripple btn-sm btn-danger">Cancel</button>
            </div>
        </form>
    </div>
</div>
<script src="~/js/Jquery3.5.1.js"></script>
<script src="~/js/jquery.sumoselect.min.js"></script>
<link href="~/js/sumoselect.min.css" rel="stylesheet" />
@*<script>
        $(document).ready(function () {
            $('#idbehavior').SumoSelect();
        }(jQuery));



    </script>*@
@*@if (@ViewBag.gameid == 5)
    {
        <script>
            $(document).ready(function () {
                debugger;
                var hidValue = $("#hidSelectedOptions").val();

                var selectedOptions = hidValue.split(",");
                for (var i in selectedOptions) {
                    var optionVal = selectedOptions[i];
                    $("select").find("option[value=" + optionVal + "]").prop("selected", "selected");
                }
                /*  $("select").multiselect('refresh');*/


            });
        </script>
    }*@


<script>
    $(document).ready(function () {


        $('#btn').on('click', function () {
            debugger;
            var valid = $("#form").valid();
            if (valid == true) {
                AddEdit();
            }
        });

        var hidValue = $("#hidSelectedOptions").val();

        var selectedOptions = hidValue.split(",");
        for (var i in selectedOptions) {
            var optionVal = selectedOptions[i];
            $("#idbehavior").find("option[value=" + optionVal + "]").prop("selected", "selected");
        }

        $("#Acclimateform").validate({
                //rules: {


                //    Url: "required",
                //    IsActive: "required",

                //},
                //messages: {


                //    Url: "Please Uploade Image ",
                //    IsActive: "Please Select a Status",
                //}
            })
    });



</script>

<style type="text/css">
    .loader {
        display: none;
        position: absolute;
        top: 75%;
        left: 50%;
        margin: -75px 0px 0px -50px;
    }
</style>
<script src="~/AppJavascript/Game5Attemptdata.js"></script>

Censio_CMS/Censio_CMS/Web_CMS/Views/Game5Attemptdata/Index.cshtml
@{ var hrefURL = Censio_CMS.Startup.GethrefURL();}
@model IEnumerable<Censio_CMS.Models.GameAttemptdataModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block full">
    <div class="block-title">
        <h2><strong> @ViewBag.PageName</strong> </h2>
    </div>
    <div class="table-responsive">

        <button type="button" onclick="location.href='@Url.Action("Create", "Game5Attemptdata")'" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i>Add</button>
        <table id="example-datatable" class="table table-vcenter table-condensed table-bordered">
            <thead>
                <tr>
                    <th class="text-center">Id</th>
                    <th class="text-center">GameName</th>
                    <th class="text-center">ChallengeName</th>
                    <th class="text-center">AttemptNo</th>
                    <th class="text-center">GoldCoins</th>
                    <th class="text-center">BehaviorScore</th>
                    <th class="text-center">TimeInSecond</th>
                    <th class="text-center">BehaviorElement</th>
                    @*<th class="text-center">ChallengeCompletedTime1</th>
                    <th class="text-center">RewardCoinsTime1</th>
                    <th class="text-center">ChallengeCompletedTime2</th>
                    <th class="text-center">RewardCoinsTime2</th>
                    <th class="text-center">FailAttemptMessage</th>
                    <th class="text-center">SuccessAttemptMessage</th>*@
                    <th class="text-center">Status</th>
                    <th class="text-center">Date and Time</th>
                    <th class="text-center">Actions</th>


                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>

                    <td class="text-center">@Html.DisplayFor(modelItem => item.IdAttempt)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.GameName)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.ChallengeName)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.AttemptNo)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.GoldCoins)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.BehaviorScore)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.TimeInSecond)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.Game5Behaviors)</td>
                    @*<td class="text-center">@Html.DisplayFor(modelItem => item.ChallengeCompletedTime1)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.RewardCoinsTime1)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.ChallengeCompletedTime2)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.RewardCoinsTime2)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.FailAttemptMessage)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.SuccessAttemptMessage)</td>*@

                    @if (item.IsActive == "A")
                    {
                        <td class="text-center">Active</td>
                    }
                    else
                    {
                        <td class="text-center"> DeActive</td>
                    }

                    <td class="text-center">@Html.DisplayFor(modelItem => item.UpdatedDateTime)</td>
                    <td class="text-center">
                        <div class="btn-group">
                            @Html.ActionLink("Edit", "Edit", new { id = item.IdAttempt }, new { @title = "Edit", @class = "glyphicon glyphicon-pencil" })
                            @*<a href="javascript:void(0)" onclick="GetAddEdit(@item.Id_Industry);" data-toggle="tooltip" title="Edit" class="btn btn-effect-ripple btn-xs btn-success"><i class="material-icons">create</i></a>*@

                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script src="~/AppJavascript/Game5Attemptdata.js"></script>