Censio_CMS/Censio_CMS/Web_CMS/Controllers/AvatarController.cs
using Censio_CMS.Web;
using Censio_CMS.Web.Filter;
using DataAccess.Data;
using Domain.Entities;
using Domain.Interfaces;
using m2ostnextservice.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace Censio_CMS.Controllers
{
    [SessionTimeout]
    public class AvatarController : Controller
    {

        int ID_ORGANIZATION = CommonFunctions.ID_ORGANIZATION;
        private readonly db_censio_betaContext DbContext;
        AESAlgorithm ency = new AESAlgorithm();
        private readonly IUnitOfWork _unitOfWork;
        string hrefURL = Startup.GethrefURL();
        private readonly IWebHostEnvironment webHostEnvironment;
        public AvatarController(IUnitOfWork unitOfWork, db_censio_betaContext context, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            DbContext = context;
            webHostEnvironment = hostEnvironment;
        }



        public ActionResult Index()
        {
            var model = this.DbContext.TblAvatar.Where(x => x.IdOrganization == ID_ORGANIZATION).ToList();
            ViewBag.PageName = "Avatar  List";

            return View(model);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TblAvatar model = this.DbContext.TblAvatar.Find(id);
            //model.Url =hrefURL + model.Url;

            if (model == null)
            {
                return HttpNotFound();
            }
            ViewBag.modelTitle = "Edit";
            return View("Create", model);
        }

        private ActionResult HttpNotFound()
        {
            throw new NotImplementedException();
        }

        public ActionResult Create()
        {
            ViewBag.modelTitle = "Add";
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> AddEditAsync(TblAvatar model)
        {
            model.IdOrganization = (int)ID_ORGANIZATION;
            model.UpdatedDateTime = DateTime.UtcNow;
            model.IdCmsUser = HttpContext.Session.GetInt32("userid");
            try
            {
                
                if (model.IdAvatar != 0)
                {
                    TblAvatar objData = (from c in this.DbContext.TblAvatar
                                                        where c.IdAvatar == model.IdAvatar
                                                        select c).FirstOrDefault();
                    if (objData != null)
                    {
                       

                        var files = HttpContext.Request.Form.Files;
                        foreach (var Image in files)
                        {
                            if (Image != null && Image.Length > 0)
                            {
                                var file = Image;

                                var uploads = Path.Combine(webHostEnvironment.WebRootPath, "UploadeImage/AvatarImg");
                                if (file.Length > 0)
                                {
                                    var fileName = model.IdOrganization + "_" + Path.GetFileName(file.FileName);
                                    using (var fileStream = new FileStream(Path.Combine(uploads, fileName), FileMode.Create))
                                    {
                                        await file.CopyToAsync(fileStream);
                                        model.Url = "UploadeImage/AvatarImg/" + fileName;
                                    }

                                }
                            }
                        }


                        objData.Url = model.Url;
                        objData.UpdatedDateTime = DateTime.UtcNow;
                        objData.IsActive = model.IsActive;
                        objData.IdOrganization = model.IdOrganization;
                        objData.IdCmsUser = model.IdCmsUser;
                        _unitOfWork.Complete();

                    }
                    return Json(new { Message = "Successfully Updated", data = 1 });

                }
                else
                {

                    _unitOfWork.Avatar.Add(model);
                    _unitOfWork.Complete();
                    var files = HttpContext.Request.Form.Files;
                    foreach (var Image in files)
                    {
                        if (Image != null && Image.Length > 0)
                        {
                            var file = Image;

                            var uploads = Path.Combine(webHostEnvironment.WebRootPath, "UploadeImage/AvatarImg");
                            if (file.Length > 0)
                            {
                                var fileName = model.IdOrganization + "_" + Path.GetFileName(file.FileName);
                                using (var fileStream = new FileStream(Path.Combine(uploads, fileName), FileMode.Create))
                                {
                                    await file.CopyToAsync(fileStream);
                                    model.Url = "UploadeImage/AvatarImg/" + fileName;
                                }

                            }
                        }
                    }
                    TblAvatar objData = (from c in this.DbContext.TblAvatar
                                                        where c.IdAvatar == model.IdAvatar
                                                        select c).FirstOrDefault();
                    if (objData != null)
                    {

                        objData.Url = model.Url;
                       

                        _unitOfWork.Complete();
                    }
                    return Json(new { Message = "Successfully Added", data = 2 });
                }



            }
            catch (Exception ex)
            {

                return Json(new { Message = "error", data = 3 });
            }
        }

    }
}

Censio_CMS/Censio_CMS/Web_CMS/Views/Avatar/Create.cshtml
@model Domain.Entities.TblAvatar
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block full">
    <div class="block-title">
        <button type="button" onclick="location.href='@Url.Action("Index", "Avatar")'" class="btn btn-primary" style="float: right; margin: 0; margin-right: 10px; margin-top: 9px; padding: 1px 13px;" data-dismiss="modal" aria-hidden="true">Back</button>
        <h2><strong>@ViewBag.modelTitle Avatar</strong> </h2>
    </div>
    <div class="table-responsive">

        <form id="form" class="push">

            <div class="modal-body">
                <div id="myAlert">
                </div>
                <div class="loader "> <img src="~/img/Loader.gif" style="height:50px;width:50px" /></div>
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">
                       
                        <div class="form-group">
                            <div class="col-sm-6">
                                <label for="checkout-payment-name">Avatar Image</label>
                                @Html.TextBoxFor(m => m.IdAvatar, new { @id = "IdAvatar", @style = "display: none;" })
                                @Html.TextBoxFor(m => m.Url, new { @id = "Url", @style = "display: none;" })
                                <input type="file" title="Upload File" class="form-control" id="file" name="file" onchange="show(this)" />
                            </div>

                             <div class="col-sm-6">
                                    <img id="url_img" style="height:100px;width:100px;" class="form-control" Style="border:solid" />
                                </div>
                         </div>
                       

                            <div class="form-group">
                                <label for="checkout-payment-name">Status</label>
                                @Html.DropDownListFor(m => m.IsActive, new List<SelectListItem>
                                       {
                                       new SelectListItem{ Text="Active", Value = "A" },
                                       new SelectListItem{ Text="Deactive", Value = "D" }}, new { @class = "form-control", @style = "width:100%;", @id = "IsActive" })
                            </div>

                       
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="btn" class="btn btn-effect-ripple btn-sm btn-success">Save</button>
                <button type="button" onclick="Close();" class="btn btn-effect-ripple btn-sm btn-danger">Cancel</button>
            </div>
        </form>
    </div>
</div>
<script src="~/js/Jquery3.5.1.js"></script>

<script>
    $(document).ready(function () {
        if ($("#Url").val() != "") {
            $('#url_img').attr('src', $("#Url").val());
        }



        $('#btn').on('click', function () {
            debugger;
            var valid = $("#form").valid();
            if (valid == true) {
                AddEdit();
            }
        });

        $("#Acclimateform").validate({
            rules: {

                
                Url: "required",
                IsActive: "required",

            },
            messages: {

              
                Url: "Please Uploade Image ",
                IsActive: "Please Select a Status",
            }
        })
    });



</script>
<style type="text/css">
    .loader {
        display: none;
        position: absolute;
        top: 75%;
        left: 50%;
        margin: -75px 0px 0px -50px;
    }
</style>
<script src="~/AppJavascript/Avatar.js"></script>

Censio_CMS/Censio_CMS/Web_CMS/Views/Avatar/Index.cshtml
@{ var hrefURL = Censio_CMS.Startup.GethrefURL();}
@model IEnumerable<Domain.Entities.TblAvatar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block full">
    <div class="block-title">
        <h2><strong> @ViewBag.PageName</strong> </h2>
    </div>
    <div class="table-responsive">

        <button type="button" onclick="location.href='@Url.Action("Create", "Avatar")'" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i>Add</button>
        <table id="example-datatable" class="table table-vcenter table-condensed table-bordered">
            <thead>
                <tr>
                    <th class="text-center">Id</th>
                    <th class="text-center">Avatar Image</th>
                    <th class="text-center">Status</th>
                    <th class="text-center">Date and Time</th>
                    <th class="text-center">Actions</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.IdAvatar)</td>


                    <td class="text-center"><img src="@(hrefURL + item.Url)" alt=" " height=100 width=100 /></td>
                    @if (item.IsActive == "A")
                    {
                        <td class="text-center">Active</td>
                    }
                    else
                    {
                        <td class="text-center"> DeActive</td>
                    }

                    <td class="text-center">@Html.DisplayFor(modelItem => item.UpdatedDateTime)</td>
                    <td class="text-center">
                        <div class="btn-group">
                            @Html.ActionLink("Edit", "Edit", new { id = item.IdAvatar }, new { @title = "Edit", @class = "glyphicon glyphicon-pencil" })
                            @*<a href="javascript:void(0)" onclick="GetAddEdit(@item.Id_Industry);" data-toggle="tooltip" title="Edit" class="btn btn-effect-ripple btn-xs btn-success"><i class="material-icons">create</i></a>*@

                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script src="~/AppJavascript/Avatar.js"></script>